# Generated by Django 3.2.25 on 2025-10-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('orcid', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('display_name_alternatives', models.JSONField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('last_known_institution', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
    ]
