# Generated by Django 4.2.25 on 2025-10-10 01:58

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCountByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('oa_works_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors_counts_by_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorIds',
            fields=[
                ('author', models.OneToOneField(db_column='author_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ids', serialize=False, to='api.author')),
                ('openalex', models.TextField(blank=True, null=True)),
                ('orcid', models.TextField(blank=True, null=True)),
                ('scopus', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('wikipedia', models.TextField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authors_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_thumbnail_url', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concepts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptAncestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'concepts_ancestors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptCountByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('oa_works_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concepts_counts_by_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptRelatedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'concepts_related_concepts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ror', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('homepage_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('image_thumbnail_url', models.TextField(blank=True, null=True)),
                ('display_name_acronyms', api.models.SafeJSONField(blank=True, null=True)),
                ('display_name_alternatives', api.models.SafeJSONField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionAssociatedInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institution_associated_institution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionCountByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('oa_works_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions_counts_by_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('alternate_titles', api.models.SafeJSONField(blank=True, null=True)),
                ('country_codes', api.models.SafeJSONField(blank=True, null=True)),
                ('hierarchy_level', models.IntegerField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('sources_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublisherCountByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('oa_works_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publishers_counts_by_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('issn_l', models.TextField(blank=True, null=True)),
                ('issn', api.models.SafeJSONField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('is_oa', models.BooleanField(null=True)),
                ('is_in_doaj', models.BooleanField(null=True)),
                ('homepage_url', models.TextField(blank=True, null=True)),
                ('works_api_url', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceCountByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('works_count', models.IntegerField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('oa_works_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sources_counts_by_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('doi', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('cited_by_count', models.IntegerField(blank=True, null=True)),
                ('is_retracted', models.BooleanField(null=True)),
                ('is_paratext', models.BooleanField(null=True)),
                ('cited_by_api_url', models.TextField(blank=True, null=True)),
                ('abstract_inverted_index', api.models.SafeJSONField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_position', models.TextField(blank=True, null=True)),
                ('raw_affiliation_string', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_authorships',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_concepts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksBestOaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_url', models.TextField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('is_oa', models.BooleanField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_best_oa_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_url', models.TextField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('is_oa', models.BooleanField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksOpenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_oa', models.BooleanField(blank=True, null=True)),
                ('oa_status', models.TextField(blank=True, null=True)),
                ('oa_url', models.TextField(blank=True, null=True)),
                ('any_repository_has_fulltext', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_open_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksPrimaryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page_url', models.TextField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('is_oa', models.BooleanField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_primary_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksReferencedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'works_referenced_works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksRelatedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'works_related_works',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptIds',
            fields=[
                ('concept', models.OneToOneField(db_column='concept_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='identifiers', serialize=False, to='api.concept')),
                ('openalex', models.TextField(blank=True, null=True)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('wikipedia', models.TextField(blank=True, null=True)),
                ('umls_aui', models.TextField(blank=True, null=True)),
                ('umls_cui', models.TextField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'concepts_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionGeo',
            fields=[
                ('institution', models.OneToOneField(db_column='institution_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='geo', serialize=False, to='api.institution')),
                ('city', models.TextField(blank=True, null=True)),
                ('geonames_city_id', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('country_code', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionIds',
            fields=[
                ('institution', models.OneToOneField(db_column='institution_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ids', serialize=False, to='api.institution')),
                ('openalex', models.TextField(blank=True, null=True)),
                ('ror', models.TextField(blank=True, null=True)),
                ('grid', models.TextField(blank=True, null=True)),
                ('wikipedia', models.TextField(blank=True, null=True)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institutions_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublisherIds',
            fields=[
                ('publisher', models.OneToOneField(db_column='publisher_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ids', serialize=False, to='api.publisher')),
                ('openalex', models.TextField(blank=True, null=True)),
                ('ror', models.TextField(blank=True, null=True)),
                ('wikidata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publishers_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceIds',
            fields=[
                ('source', models.OneToOneField(db_column='source_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ids', serialize=False, to='api.source')),
                ('openalex', models.TextField(blank=True, null=True)),
                ('issn_l', models.TextField(blank=True, null=True)),
                ('issn', api.models.SafeJSONField(blank=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
                ('wikidata', models.TextField(blank=True, null=True)),
                ('fatcat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sources_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkBiblio',
            fields=[
                ('work', models.OneToOneField(db_column='work_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='biblio', serialize=False, to='api.work')),
                ('volume', models.TextField(blank=True, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('first_page', models.TextField(blank=True, null=True)),
                ('last_page', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_biblio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksIds',
            fields=[
                ('work', models.OneToOneField(db_column='work_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='work_ids', serialize=False, to='api.work')),
                ('openalex', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, db_index=True, null=True)),
                ('mag', models.BigIntegerField(blank=True, null=True)),
                ('pmid', models.TextField(blank=True, null=True)),
                ('pmcid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_ids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorksMesh',
            fields=[
                ('work', models.OneToOneField(db_column='work_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='mesh_terms', serialize=False, to='api.work')),
                ('descriptor_ui', models.TextField(blank=True, null=True)),
                ('descriptor_name', models.TextField(blank=True, null=True)),
                ('qualifier_ui', models.TextField(blank=True, null=True)),
                ('qualifier_name', models.TextField(blank=True, null=True)),
                ('is_major_topic', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works_mesh',
                'managed': False,
            },
        ),
    ]
